package com.example.pluck.ui.story

import android.content.ClipData
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.net.Uri
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import android.text.format.DateFormat
import androidx.core.content.FileProvider
import com.example.pluck.domain.model.StoryMood
import java.io.File
import java.io.FileOutputStream
import java.util.Date

/**
 * Renders private, local PNG share cards from an existing story.
 * No image is generated by a model and files are written only to the app cache for Android Sharesheet.
 */
object StoryShareRenderer {
    private const val WIDTH = 1080
    private const val HEIGHT = 1350
    private const val HORIZONTAL_PADDING = 86

    fun quoteIntent(
        context: Context,
        title: String,
        content: String,
        mood: StoryMood,
        createdAt: Long
    ): Intent = shareSingle(
        context = context,
        uri = writeCard(
            context = context,
            fileName = "pluck_quote_${System.currentTimeMillis()}.png",
            title = title,
            body = content.quoteExcerpt(),
            mood = mood,
            createdAt = createdAt,
            pageLabel = "A PLUCK QUOTE"
        ),
        chooserTitle = "Share quote card"
    )

    fun carouselIntent(
        context: Context,
        title: String,
        content: String,
        mood: StoryMood,
        createdAt: Long
    ): Intent {
        val cards = buildList {
            add(
                writeCard(
                    context = context,
                    fileName = "pluck_cover_${System.currentTimeMillis()}.png",
                    title = title,
                    body = "A ${mood.displayName.lowercase()} story, shaped by one real day.",
                    mood = mood,
                    createdAt = createdAt,
                    pageLabel = "PLUCK ORIGINAL"
                )
            )
            content.cardPages(maxPages = 5).forEachIndexed { index, page ->
                add(
                    writeCard(
                        context = context,
                        fileName = "pluck_story_${System.currentTimeMillis()}_$index.png",
                        title = title,
                        body = page,
                        mood = mood,
                        createdAt = createdAt,
                        pageLabel = "CHAPTER ${index + 1}"
                    )
                )
            }
        }
        return Intent(Intent.ACTION_SEND_MULTIPLE).apply {
            type = "image/png"
            putParcelableArrayListExtra(Intent.EXTRA_STREAM, ArrayList(cards))
            clipData = ClipData.newRawUri("Pluck story cards", cards.first())
            cards.drop(1).forEach { clipData?.addItem(ClipData.Item(it)) }
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }.let { Intent.createChooser(it, "Share story cards") }
    }

    private fun shareSingle(context: Context, uri: Uri, chooserTitle: String): Intent =
        Intent(Intent.ACTION_SEND).apply {
            type = "image/png"
            putExtra(Intent.EXTRA_STREAM, uri)
            clipData = ClipData.newRawUri("Pluck share card", uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }.let { Intent.createChooser(it, chooserTitle) }

    private fun writeCard(
        context: Context,
        fileName: String,
        title: String,
        body: String,
        mood: StoryMood,
        createdAt: Long,
        pageLabel: String
    ): Uri {
        val bitmap = Bitmap.createBitmap(WIDTH, HEIGHT, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        val palette = mood.palette()
        canvas.drawColor(palette.background)

        val accentPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = palette.accent }
        canvas.drawRoundRect(
            RectF(HORIZONTAL_PADDING.toFloat(), 84f, (WIDTH - HORIZONTAL_PADDING).toFloat(), 96f),
            6f,
            6f,
            accentPaint
        )

        val labelPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = palette.foreground
            textSize = 28f
            letterSpacing = 0.14f
            typeface = android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT, android.graphics.Typeface.BOLD)
        }
        canvas.drawText(pageLabel, HORIZONTAL_PADDING.toFloat(), 154f, labelPaint)

        val titlePaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = palette.foreground
            textSize = 64f
            typeface = android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT, android.graphics.Typeface.BOLD)
        }
        drawTextBlock(canvas, title, titlePaint, 212, maxLines = 4)

        val bodyPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = palette.foreground
            textSize = 38f
            typeface = android.graphics.Typeface.create(android.graphics.Typeface.DEFAULT, android.graphics.Typeface.NORMAL)
        }
        drawTextBlock(canvas, body, bodyPaint, 566, maxLines = 13)

        val footerPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
            color = palette.foreground
            alpha = 190
            textSize = 26f
        }
        val date = DateFormat.getMediumDateFormat(context).format(Date(createdAt))
        canvas.drawText("${mood.displayName.uppercase()}  •  $date", HORIZONTAL_PADDING.toFloat(), (HEIGHT - 104).toFloat(), footerPaint)
        canvas.drawText("Made with Pluck", HORIZONTAL_PADDING.toFloat(), (HEIGHT - 62).toFloat(), footerPaint)

        val directory = File(context.cacheDir, "story_shares").apply { mkdirs() }
        val output = File(directory, fileName)
        FileOutputStream(output).use { stream -> bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream) }
        bitmap.recycle()
        return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", output)
    }

    private fun drawTextBlock(
        canvas: Canvas,
        value: String,
        paint: TextPaint,
        top: Int,
        maxLines: Int
    ) {
        val text = value.trim()
        val layout = StaticLayout.Builder
            .obtain(text, 0, text.length, paint, WIDTH - (HORIZONTAL_PADDING * 2))
            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
            .setIncludePad(false)
            .setLineSpacing(10f, 1f)
            .setMaxLines(maxLines)
            .setEllipsize(android.text.TextUtils.TruncateAt.END)
            .build()
        canvas.save()
        canvas.translate(HORIZONTAL_PADDING.toFloat(), top.toFloat())
        layout.draw(canvas)
        canvas.restore()
    }

    private fun String.quoteExcerpt(): String =
        trim().split(Regex("\\n\\s*\\n")).firstOrNull().orEmpty().take(460).ifBlank { trim().take(460) }

    private fun String.cardPages(maxPages: Int): List<String> {
        val words = trim().split(Regex("\\s+"))
        if (words.isEmpty()) return listOf("Your story is ready in Pluck.")
        val pageSize = 105
        return words.chunked(pageSize).take(maxPages).map { it.joinToString(" ") }
    }

    private data class Palette(val background: Int, val foreground: Int, val accent: Int)

    private fun StoryMood.palette(): Palette = when (this) {
        StoryMood.CINEMATIC -> Palette(Color.rgb(30, 47, 68), Color.WHITE, Color.rgb(152, 206, 255))
        StoryMood.MYSTERIOUS -> Palette(Color.rgb(47, 37, 71), Color.WHITE, Color.rgb(211, 180, 255))
        StoryMood.WHIMSICAL -> Palette(Color.rgb(53, 78, 68), Color.WHITE, Color.rgb(170, 235, 196))
        StoryMood.WARM -> Palette(Color.rgb(112, 61, 43), Color.WHITE, Color.rgb(255, 204, 150))
        StoryMood.ADVENTUROUS -> Palette(Color.rgb(45, 76, 91), Color.WHITE, Color.rgb(167, 224, 236))
        StoryMood.DARK -> Palette(Color.rgb(35, 35, 40), Color.WHITE, Color.rgb(230, 185, 115))
    }
}
